version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
    # - $DB_PORT:$DB_PORT
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  fiverr_be:
    depends_on:
      - mysql_db
    build: .
    # image: hungduong2k/fiverr_api
    container_name: fiverr_be
    env_file: .env
    environment:
      - DATABASE_URL=$DB_URL_DOCKER
      - VIRTUAL_PORT=8080
    ports:
      # machinePort:appPort
      - "8080:8080"
    networks:
      - node-network

volumes:
  mysql_db:
    driver: local

networks:
  node-network:
  